#+HTML_HEAD: <style>body { max-width: 80ex; margin: auto; font: 1.15em sans-serif; }</style>
#+TITLE: Design and implementation notes
* Examples of commands
** Adding task with description
In TaskWarrior, a task can be added from the shell simply using the following
syntax:
#+BEGIN_EXAMPLE
$ task add "this is a new task"
Created task 1.
#+END_EXAMPLE
TWD also uses the /add/ command to add new tasks. The task can be given a
description by specifying a value for the /desc/ field. We use curly braces as
quotation marks to better avoid conflicts with user strings. Thus, the
equivalent command in TWD is:
#+BEGIN_EXAMPLE
> add desc:{this is a new task}
1   todo   this is a new task   1.00
#+END_EXAMPLE
Since /desc/ is the most common field, it is chosen by default if no other field
is specified. This means that the following command is equivalent to the one
above:
#+BEGIN_EXAMPLE
> add {this is a new task}
1   todo   this is a new task   1.00
#+END_EXAMPLE
** Adding task with tags
When adding a task in TaskWarrior, it is possible to specify any number of tags
with the following syntax:
#+BEGIN_EXAMPLE
$ task add +tag1 +tag2 "this is a new task" +tag3
Created task 1.
#+END_EXAMPLE
The equivalent syntax in TWD is:
#+BEGIN_EXAMPLE
> add tag:{tag1} tag:{tag2} desc:{this is a new task} tag:{tag3}
1 | todo | tag1 tag2 tag3 | this is a new task | 1.00
#+END_EXAMPLE
In this example, the tags contain no spaces, so we can simply write:
#+BEGIN_EXAMPLE
> add tag:tag1 tag:tag2 desc:{this is a new task} tag:tag3
#+END_EXAMPLE
Additionally, it is possible to abbreviate =tag:tag-name= as =#tag-name= for any
=tag-name=, which means that the above command can actually be written as:
#+BEGIN_EXAMPLE
> add #tag1 #tag2 {this is a new task} #tag3
#+END_EXAMPLE
