version: 2
jobs:
  build:
    working_directory: ~/untask
    docker:
      - image: c2d7fa/racket:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          keys:
            - racket-deps-4-{{checksum "info.rkt"}}
      - run:
          name: Install rackunit-fancy-runner directory (workaround for pkgd.racket-lang.org being broken)
          command: |
            cd ~
            if [ ! -d rackunit-fancy-runner ]; then
              git clone 'https://github.com/c2d7fa/rackunit-fancy-runner.git'
              cd rackunit-fancy-runner
            else
              cd rackunit-fancy-runner
              git pull
            fi
            raco pkg install --auto --no-setup --skip-installed
      - run:
          name: Update and install missing dependencies
          command: |
            raco pkg install --auto --no-setup --skip-installed
            raco pkg update --all
      - save_cache:
          name: Cache dependencies
          key: racket-deps-4-{{checksum "info.rkt"}}
          paths:
            - ~/.racket/
            - ~/rackunit-fancy-runner
      - run:
          name: Run tests
          command: |
            Xvfb :1 -screen 0 1024x768x16 &
            DISPLAY=:1 racket tests.rkt

